version: '3.8'

services:
  simulator:
    image: seismic-signal-simulator:multiarch_v1
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: seismic_hq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  broker:
    build: ./source/broker # Assicurati che il percorso sia corretto
    depends_on:
      - simulator
    environment:
      - SIMULATOR_URL=http://simulator:8080
    restart: always

  processor_1:
    build: ./source/processor
    depends_on:
      - broker
    restart: always

  processor_2:
    build: ./source/processor
    depends_on:
      - broker
    restart: always

  gateway:
    build: ./source/gateway
    ports:
      - "8000:8000"
    depends_on:
      - processor_1
      - processor_2
      - db
    restart: always

frontend:
    build: ./source/frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway # La dashboard parlerà con il Gateway, non direttamente con le repliche