services:
  simulator:
    image: seismic-signal-simulator:multiarch_v1
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: seismic_hq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  broker:
    build: ./source/broker
    depends_on:
      simulator:
        condition: service_healthy # Ora il broker aspetta che l'healthcheck del simulatore sia OK
    environment:
      SIMULATOR_URL: "http://simulator:8080"
