services:
  simulator:
    image: seismic-signal-simulator:multiarch_v1
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: seismic_hq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  broker:
    build: ./source/broker
    depends_on:
      - simulator
    environment:
      SIMULATOR_URL: "http://simulator:8080"